name: Security & Deployment Pipeline

permissions:
  contents: read
  actions: read
  security-events: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    name: Security Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy on source code
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          exit-code: 1
          ignore-unfixed: true

      - name: Run Checkov on Terraform code
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .

      - name: Run Gitleaks to detect secrets
        uses: gitleaks/gitleaks-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
