name: Security & Deployment Pipeline

permissions:
  contents: read
  actions: read
  security-events: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    name: Security Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy on source code
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          exit-code: 1
          ignore-unfixed: true

      - name: Run Checkov on Terraform code
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .

      - name: Check file permissions
        run: ls -l . && ls -l .github/workflows/

      - name: Set write permissions for specific files
        run: chmod 666 results.sarif || true

      - name: Fix permissions for results.sarif
        run: chmod 777 .

      - name: Get Latest Gitleaks Version
        run: | 
          curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest | jq -r '.tag_name'

      - name: Install Gitleaks
        run: |
          sudo apt update && sudo apt install -y jq  # Assurer que jq est installé
          DOWNLOAD_URL="https://github.com/gitleaks/gitleaks/releases/download/v8.24.0/gitleaks_8.24.0_linux_x64.tar.gz"
          echo "Downloading: $DOWNLOAD_URL"
          curl -sSL -o gitleaks.tar.gz "$DOWNLOAD_URL"

          tar -xzf gitleaks.tar.gz
          mv gitleaks /usr/local/bin/gitleaks

          chmod +x /usr/local/bin/gitleaks

          ls -l /usr/local/bin/gitleaks
          gitleaks --version  # Vérifier que Gitleaks fonctionne

      - name: Run Gitleaks manually
        run: |
          gitleaks detect --redact -v --exit-code=2 --report-format=sarif --report-path=/tmp/gitleaks-results.sarif
